### ISSUE TITLE
wrong links to normalised microarray data for metagx dataset

### ISSUE THREAD

**Issue by noskill** [singnet/cancer#33]
links to normalized data in cancer/data/metaGxBreast/microarray data/README.md point to not normalised files.

**Comment by noskill** [comment]
for example mGXrlNormBatch.tar.xz points to https://snet-bio-data.s3.us-west-2.amazonaws.com/example15bmc/mGXnoNormBatch.tar.xz

**Comment by mjsduncan** [comment]
fixed
